spring.application.name=Dev  Stu App

spring.config.import=optional:classpath:credentials.properties
spring.messages.basename=validation

# Server 8080 443 80
server.port=443
#server.ssl.enabled=true


# Swagger
#springdoc.api-docs.enabled=true
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.enabled=true
#springdoc.swagger-ui.path=/swagger-ui/index.html


# MongoDB ??
spring.data.mongodb.uri=${mongodb.uri}
spring.data.mongodb.username=${mongodb.username}
spring.data.mongodb.password=${mongodb.password}


# HTTPS
server.ssl.key-store=classpath:certs/keystore.p12
server.ssl.key-store-password=${key_store_password}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=monstu
#server.ssl.client-auth=none

# HTTPS - (Build Setting)
#server.ssl.key-store=classpath:certs/origin-ca.p12
#server.ssl.key-store-password=${key_store_password}
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=monstu
#server.ssl.client-auth=none